volumes:
  tftp_data:
    external: true
    name: ${TFTP_VOLUME_NAME}

services:
  tftp-server:
    build: .
    container_name: 12-tftp-server
    restart: unless-stopped
    network_mode: host
    ports:
      - 69:69/udp
    volumes:
      - tftp_data:/var/lib/tftpboot
