volumes:
  tftp_data:
    external: true
    name: ${TFTP_VOLUME_NAME}

services:
  tftp-server:
    build: .
    container_name: ${CONTAINER_NAME:tftp-server}
    restart: unless-stopped
    ports:
      - 69:69/udp"
    volumes:
      - tftp_data:/var/lib/tftpboot