version: '3.8'

services:
  12-tftp-server:
    build: .
    container_name: 12-tftp-server
    restart: unless-stopped
    ports:
      - "69:69/udp"
    volumes:
      - ${TFTP_ROOT}:/var/lib/tftpboot